spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/lms_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# ?????: validate ?????? update!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

server.port=8080
spring.security.user.name=user
spring.security.user.password=123